### PR TITLE
auto_comment.yml changed to send different responses to owner's and …

### LINKED ISSUE #29: Fix Github Action Workflows | auto_assign.yml
# Fix
/assign or other comments should only work if the issue is not assigned to someone

image

### PR DESCRIPTION
**Pull request by aryanas159**
auto_comment.yml changed to send different responses to issues created by owners and contributors.
fixes #29 
I couldn't check if the change fixes the issue.
I have added an if statement which checks if the author is the owner or not and sends responses accordingly.

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
make a new PR ,
The code is showing error when i create an issue

image

**Comment by Swapnil-Singh-99** [comment]
@aryanas159

**Comment by aryanas159** [comment]
@Swapnil-Singh-99 I couldn't simulate this locally, solving this issue may require heavy debugging to solve, which isn't possible locally.

**Comment by Swapnil-Singh-99** [comment]
> @Swapnil-Singh-99 I couldn't simulate this locally, solving this issue may require heavy debugging to solve, which isn't possible locally.

ok Np
You can work on other issue,
But create new issues

**Pull request merged**
