### PR TITLE
adding a meme generator script

### PR DESCRIPTION
**Pull request by amanmakhija**
Added a meme generator script. To run you just have to click the run all button.

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@amanmakhija add an issue for the same PR

**Comment by amanmakhija** [comment]
> @amanmakhija add an issue for the same PR

I didn't get it.

**Comment by amanmakhija** [comment]
> @amanmakhija add an issue for the same PR

#106 is the issue for this PR and has already been opened and assigned to me.

**Comment by Swapnil-Singh-99** [comment]
@amanmakhija 
image
Getting error while executing
Please fix or provide a requirements.txt for the script

**Comment by amanmakhija** [comment]
> @amanmakhija image Getting error while executing Please fix or provide a requirements.txt for the script

I've pushed the updated code for the meme generator issue.

**Comment by Swapnil-Singh-99** [comment]
Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
