### PR TITLE
completed password strength checker

### PR DESCRIPTION
**Pull request by Transyltooniaa**
This Python script is a password strength checker tool that allows users to input passwords and evaluates their strength based on certain criteria. It includes the following features:

Password Generation: It generates a strong random password of at least 12 characters, combining digits, uppercase letters, lowercase letters, and symbols to ensure complexity.

Password Strength Rating: The script uses the zxcvbn library to rate the strength of the provided password. It categorizes passwords as either "Weak" or "Strong" based on their complexity and checks them against a provided weak wordlist to ensure they are not commonly used.

Suggested Strong Password: If a password is rated as "Weak," it suggests a strong random password generated earlier for the user to consider using instead.

Custom Wordlists: Users can provide their custom wordlists for both weak and banned passwords.

Interactive Usage: It allows users to test multiple passwords in a loop and provides strength feedback for each password entered.

In summary, this script helps users assess the strength of their passwords and provides recommendations for stronger alternatives when needed. It also gives users the flexibility to customize wordlists for more tailored password checks.

### CODE REVIEW

**Comment by Transyltooniaa** [comment]
password_strength

Here is a sample picture for the above code ! .... Do let me know if something else was expected. Thanking you for your time and consideration

**Comment by Transyltooniaa** [comment]
issue #14

**Comment by Swapnil-Singh-99** [comment]
@Transyltooniaa delete the Conflicting files   ".DS_Store"

**Comment by Transyltooniaa** [comment]
Please check I have removed the conflicting files

**Pull request merged**
