### PR TITLE
Desktop notifier task

### LINKED ISSUE #6: Desktop Notifier
Make a desktop notifier that will notify for a specific task on our laptop/computer

### PR DESCRIPTION
**Pull request by Parvezkhan0**
Fixes #6

### CODE REVIEW

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 Did I made some mistake ? why that one checks failed

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 add a time after the the notification will visible

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 I had updated the pr by adding a timeout parameter

**Comment by Swapnil-Singh-99** [comment]
Good Job 👍

Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
