### PR TITLE
feat: add Talkingbot

### LINKED ISSUE #148: Add a chatbot project
# This issue is to add a project of a bot
- while working on this issue you need to add any bot that has been scripted using python
- the project needs to contain an md file describing the project you've added

### PR DESCRIPTION
**Pull request by Srish-ty**
# This pr adds a project of talking bot
- The Adrien bot takes texts as input and responds with speech
- - using its text to speech module
- resolves #148

### CODE REVIEW

**Comment by Srish-ty** [comment]
@Swapnil-Singh-99 , Please review the pr and add relevant label.
This contribution is under hacktoberfest.

**Comment by Swapnil-Singh-99** [comment]
@Srish-ty Please add an issue for the same
I will then review it and merge and assign labels

**Comment by Srish-ty** [comment]
> @Srish-ty Please add an issue for the same I will then review it and merge and assign labels

The issue has been added and pr is linked to it #148 

Thank you for your response.

**Comment by Swapnil-Singh-99** [comment]
Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
