### PR TITLE
feat: added co2 predictor model

### LINKED ISSUE #147: Feat : add an ML model
# Adding an ML project to the repo
- This issue is to add a project related to any ML model

### PR DESCRIPTION
**Pull request by Srish-ty**
# CO2 emmision predictor
- This is a Machine learning model which
- It takes input of number of car engines, size of engine etc.
- And predicts what can be the possible emmission of CO2 by the new model of car
- The model uses linear regression 

fixes #147 issue

### CODE REVIEW

**Comment by Srish-ty** [comment]
@Swapnil-Singh-99  , Please review the pr and add relevant label.
This contribution is under hacktoberfest.

**Comment by Srish-ty** [comment]
fixes #147

**Comment by Srish-ty** [comment]
@Swapnil-Singh-99 please review and merge the pr or atleast add relevant labels.

**Comment by Swapnil-Singh-99** [comment]
Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
