### PR TITLE
Add Python script to reverse a number

### LINKED ISSUE #4: Add script to reverse a number
Hi,

I'd like to start working on the above issue. A simple script that reverses a number sounds like a good first addition to this repo.

Thanks,
<i>Ravi<i>

### PR DESCRIPTION
**Pull request by Parvezkhan0**
Fixes #4

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 Please follow the script addition pattern and add the script under a folder named "Reverse_a_number"

**Comment by Parvezkhan0** [comment]
Is it correct now?

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 add the script under the folder

**Comment by Parvezkhan0** [comment]
I am really sorry about my previous mistake. I just wanted to contribute first that is why I made those pr

**Comment by Swapnil-Singh-99** [comment]
> I am really sorry about my previous mistake. I just wanted to contribute first that is why I made those pr

You can even create our own issue I will assign them, then you can start working and create a PR

**Comment by Swapnil-Singh-99** [comment]
Good Job 👍

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Swapnil-Singh-99** [comment]
Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
