### PR TITLE
Added Twitter Motivational Quotes Bot Script

### PR DESCRIPTION
**Pull request by Aryainguz**
*I added Twitter Bot that tweets motivation quotes script in python
*Anyone can easily host this script with their right credentials on pythonanywhere for free and this also uses free twitter api

*This solves #25

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@Aryainguz Please make a readme file explaining how to get tweeter api and tokens
Also add one requirements.txt

**Comment by Aryainguz** [comment]
> @Aryainguz Please make a readme file explaining how to get tweeter api and tokens
> Also add one requirements.txt

Okay sure

**Comment by Aryainguz** [comment]
> @Aryainguz Please make a readme file explaining how to get tweeter api and tokens Also add one requirements.txt

@Swapnil-Singh-99 I have successfully added requirements.txt and readme

**Comment by Swapnil-Singh-99** [comment]
Good Job 👍

Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
