### PR TITLE
added task schedule

### PR DESCRIPTION
**Pull request by Transyltooniaa**
I have made a task manger using tkinter module of python... Please review my PR and let me know if you expected something else . Once again thanks for giving me the opportunity

### CODE REVIEW

**Comment by Transyltooniaa** [comment]
Screenshot 2023-09-30 at 8 01 33 PM

Here is a sample image of the program... you may run it on your system but before that

``` pip install tkinter ```

Since I am using macos .... the background colours are not clearly visible .... I think it will give a good theme on windows

**Comment by Swapnil-Singh-99** [comment]
@Transyltooniaa The task.db is not working make the tasks be visible on the GUI after the program runs again

**Comment by Swapnil-Singh-99** [comment]
Good Job 👍
Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Swapnil-Singh-99** [comment]
@Transyltooniaa Comment #{issue_number}

**Comment by Transyltooniaa** [comment]
issue number #18

**Comment by Transyltooniaa** [comment]
I think it is #9  ...

**Comment by Swapnil-Singh-99** [comment]
Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
